# Site
name: "Muneeb Ahmed"
title: "Muneeb Ahmed | Blog"
description: "Reading here will lead to exploration. I talk Computer Science, mostly. Life, sometimes."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blog
google_analytics: 'G-SKXP440FE6'
disqus: 'disqus_HfCUcwZYNx'
mailchimp-list: 'https://github.us14.list-manage.com/subscribe/post?u=fab8368838238bf1b859e24bd&id=02b1332e1a'
include: ["_pages"]
permalink: /:title/
email: muneebpandith@gmail.com

# Authors
authors:
  muneeb:
    name: Muneeb Ahmed
    display_name: Muneeb
    web: https://muneebpandith.github.io/
    avatar: https://muneebpandith.github.io/files/media/me.jpeg
    twitter: https://twitter.com/munneeb
    description: "Doctoral Scholar at IIT Delhi"
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

remote_theme: jekyll-theme-cayman